/**
 * Express Type Extensions for NexusProseCreator
 *
 * Extends Express Request object with custom properties:
 * - requestId: Unique identifier for request tracing
 * - userId: Authenticated user ID (if authenticated)
 * - startTime: Request start timestamp for latency tracking
 */

import { Logger } from 'winston';

declare global {
  namespace Express {
    interface Request {
      /**
       * Unique identifier for request tracing
       * Generated by middleware for each incoming request
       */
      requestId: string;

      /**
       * Request-specific logger with requestId context
       * Use this for all logging within request handlers
       */
      logger: Logger;

      /**
       * Request start time (milliseconds since epoch)
       * Used for calculating request latency
       */
      startTime: number;

      /**
       * Authenticated user ID (if authenticated)
       * Populated by authentication middleware
       */
      userId?: string;

      /**
       * Authenticated user email (if authenticated)
       * Populated by authentication middleware
       */
      userEmail?: string;

      /**
       * User roles/permissions (if authenticated)
       * Populated by authentication middleware
       */
      userRoles?: string[];
    }
  }
}

export {};
